# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 烈焰 
email: fegoing@163.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: >- # "执着 * 深刻 * 有温度"
  执着 * 深刻 * 有温度
#description: >- # sdfasdfasf 
  #Write an awesome description for your new site here. You can edit this
# "执着 * 深刻 * 有温度"


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lieyan.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: showkilling 
github_username: jing4seven 

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - disqus-for-jekyll

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#theme: jekyll-theme-awesome
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout

#disqus.shortname: disqus_0NCc7cpeFM
#disqus:
#    shortname: "disqus_0NCc7cpeFM"
#    noscript: "Please switch your noscript tag on."

# pagnation
paginate: 10
paginate_path: "blog/page:num"

# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8zNjE4OC8xMjcyMw




